/**
 * VOYAGES_DATA — Données centralisées de tous les voyages
 * Utilisé par : voyages.js (carte D3, grille) et voyage.js (page dédiée)
 * Structure   : une entrée par voyage, triée par ordre chronologique (nr)
 * Source      : VOYAGES_DATA_v1.3.xlsx — éditer le xlsx, puis regénérer ce fichier
 *
 * Champs :
 *   nr                 — numéro chronologique du voyage
 *   id                 — identifiant unique ex: tanzanie-202407 (URL + dossier images)
 *   country            — pays visité (peut contenir ";" si 2 pays)
 *   continent          — continent (stats + filtre futur)
 *   published          — true/false — seuls les voyages published:true sont affichés
 *   travellers         — tableau de voyageurs (donnée privée, jamais affichée)
 *   date_dep           — date départ YYYY-MM-DD (null si inconnue)
 *   date_ret           — date retour YYYY-MM-DD (null si inconnue)
 *   coords             — [longitude, latitude] pays — haversine fallback
 *   trip_type          — tableau : ["Séjour"] / ["Roadtrip"] / ["Safari"] / combinés
 *   airport_dep        — nom aéroport de départ
 *   airport_dep_coords — [longitude, latitude] aéroport départ — carte D3 + haversine
 *   airport_ret        — nom aéroport de retour
 *   airport_ret_coords — [longitude, latitude] aéroport retour — itinéraire roadtrip
 *   stops              — tableau des étapes (itinéraire voyage.html)
 *   photos             — nombre de photos disponibles (0 = placeholder lettre)
 *   cover              — numéro de la photo de couverture (grille + hero). Défaut 1.
 *   intro              — texte d'accroche (non affiché pour l'instant)
 *   comments           — notes personnelles (jamais affichées sur le site)
 */

const VOYAGES_DATA = [
  {
    nr:                 1,
    id:                 "hongrie-201010",
    country:            "Hongrie",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           null,
    date_ret:           null,
    coords:             [19.0, 47.5],
    trip_type:          ["Séjour"],
    airport_dep:        "Budapest",
    airport_dep_coords: [19.2556, 47.4369],
    airport_ret:        "Budapest",
    airport_ret_coords: [19.2556, 47.4369],
    stops:              ["Budapest"],
    photos:             0,
    cover:              1,
    intro:              "Premier voyage en avion, premier dépaysement. Budapest avec ses bains thermaux, son architecture austro-hongroise et ses rives du Danube illuminées la nuit.",
    comments:           null,
  },
  {
    nr:                 2,
    id:                 "finlande-201106",
    country:            "Finlande",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2011-07-21",
    date_ret:           "2011-07-29",
    coords:             [25.0, 60.2],
    trip_type:          ["Séjour"],
    airport_dep:        "Helsinki",
    airport_dep_coords: [24.9633, 60.3172],
    airport_ret:        "Helsinki",
    airport_ret_coords: [24.9633, 60.3172],
    stops:              ["Helsinki"],
    photos:             0,
    cover:              1,
    intro:              "Helsinki en été, quand le soleil ne se couche presque pas. Une ville propre, silencieuse, avec la mer partout.",
    comments:           null,
  },
  {
    nr:                 3,
    id:                 "irlande-201207",
    country:            "Irlande",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2012-07-23",
    date_ret:           "2012-07-30",
    coords:             [-8.2, 53.1],
    trip_type:          ["Séjour"],
    airport_dep:        "Dublin",
    airport_dep_coords: [-6.27, 53.4213],
    airport_ret:        "Dublin",
    airport_ret_coords: [-6.27, 53.4213],
    stops:              ["Dublin"],
    photos:             0,
    cover:              1,
    intro:              "Dublin et ses pubs, ses façades colorées et son sens de l'humour.",
    comments:           null,
  },
  {
    nr:                 4,
    id:                 "bolivie-201207",
    country:            "Bolivie",
    continent:          "Amérique du Sud",
    published:          true,
    travellers:         ["Ste"],
    date_dep:           null,
    date_ret:           null,
    coords:             [-68.1, -16.5],
    trip_type:          ["Roadtrip"],
    airport_dep:        "La Paz",
    airport_dep_coords: [-68.1922, -16.5133],
    airport_ret:        "La Paz",
    airport_ret_coords: [-68.1922, -16.5133],
    stops:              ["La Paz", "Titicaca"],
    photos:             0,
    cover:              1,
    intro:              "La Bolivie :)",
    comments:           null,
  },
  {
    nr:                 5,
    id:                 "espagne-201210",
    country:            "Espagne",
    continent:          "Europe",
    published:          true,
    travellers:         ["Ste", "Tip", "Mar", "Gaé"],
    date_dep:           "2012-10-17",
    date_ret:           "2012-10-20",
    coords:             [-3.7, 40.4],
    trip_type:          ["Séjour"],
    airport_dep:        "Barcelone",
    airport_dep_coords: [2.0785, 41.2971],
    airport_ret:        "Barcelone",
    airport_ret_coords: [2.0785, 41.2971],
    stops:              ["Barcelone"],
    photos:             0,
    cover:              1,
    intro:              "Barcelone entre Gaudí et la Barceloneta. Lumière méditerranéenne, énergie permanente.",
    comments:           null,
  },
  {
    nr:                 6,
    id:                 "pologne-201212",
    country:            "Pologne",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2012-12-31",
    date_ret:           null,
    coords:             [21.0, 52.2],
    trip_type:          ["Séjour"],
    airport_dep:        "Varsovie",
    airport_dep_coords: [20.9671, 52.1657],
    airport_ret:        "Varsovie",
    airport_ret_coords: [20.9671, 52.1657],
    stops:              ["Varsovie"],
    photos:             0,
    cover:              1,
    intro:              "Varsovie en plein hiver, à quelques jours du Nouvel An. Une ville qui surprend par son énergie et son histoire.",
    comments:           null,
  },
  {
    nr:                 7,
    id:                 "norvege-201407",
    country:            "Norvège",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2014-07-27",
    date_ret:           "2014-08-06",
    coords:             [10.7, 59.9],
    trip_type:          ["Séjour"],
    airport_dep:        "Stavanger",
    airport_dep_coords: [5.6378, 58.8768],
    airport_ret:        "Stavanger",
    airport_ret_coords: [5.6378, 58.8768],
    stops:              ["Stavanger"],
    photos:             0,
    cover:              1,
    intro:              "Premier contact avec la Norvège. Stavanger, le Lysefjord, et la montée au Preikestolen.",
    comments:           null,
  },
  {
    nr:                 8,
    id:                 "portugal-201410",
    country:            "Portugal",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2014-10-13",
    date_ret:           null,
    coords:             [-9.1, 38.7],
    trip_type:          ["Séjour"],
    airport_dep:        "Lisbonne",
    airport_dep_coords: [-9.1359, 38.7756],
    airport_ret:        "Lisbonne",
    airport_ret_coords: [-9.1359, 38.7756],
    stops:              ["Lisbonne"],
    photos:             0,
    cover:              1,
    intro:              "Lisbonne et ses sept collines, ses azulejos, son fado. Une ville mélancolique et lumineuse.",
    comments:           null,
  },
  {
    nr:                 9,
    id:                 "norvege-201507",
    country:            "Norvège",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste", "Ren", "Dan"],
    date_dep:           "2015-07-06",
    date_ret:           "2015-07-13",
    coords:             [10.7, 59.9],
    trip_type:          ["Séjour"],
    airport_dep:        "Stavanger",
    airport_dep_coords: [5.6378, 58.8768],
    airport_ret:        "Stavanger",
    airport_ret_coords: [5.6378, 58.8768],
    stops:              ["Ogna"],
    photos:             0,
    cover:              1,
    intro:              "Retour à Stavanger, cette fois pour explorer plus loin. Les fjords, les villages de pêcheurs.",
    comments:           null,
  },
  {
    nr:                 10,
    id:                 "turquie-201510",
    country:            "Turquie",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2015-10-19",
    date_ret:           "2015-10-24",
    coords:             [35.2, 38.9],
    trip_type:          ["Séjour"],
    airport_dep:        "Istanbul",
    airport_dep_coords: [28.8141, 40.9769],
    airport_ret:        "Istanbul",
    airport_ret_coords: [28.8141, 40.9769],
    stops:              ["Istanbul"],
    photos:             0,
    cover:              1,
    intro:              "Istanbul à la croisée de deux continents. Le Grand Bazar, Sainte-Sophie, le Bosphore.",
    comments:           null,
  },
  {
    nr:                 11,
    id:                 "usa-201602",
    country:            "États-Unis",
    continent:          "Amérique du Nord",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2016-02-18",
    date_ret:           "2016-02-26",
    coords:             [-74.0, 40.7],
    trip_type:          ["Séjour"],
    airport_dep:        "New York",
    airport_dep_coords: [-73.7789, 40.6413],
    airport_ret:        "New York",
    airport_ret_coords: [-73.7789, 40.6413],
    stops:              ["New York"],
    photos:             0,
    cover:              1,
    intro:              "New York en février, sous un froid mordant. Manhattan, Central Park enneigé.",
    comments:           null,
  },
  {
    nr:                 12,
    id:                 "portugal-201706",
    country:            "Portugal",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste", "Kri", "Yve", "Dan", "Mat"],
    date_dep:           "2017-06-02",
    date_ret:           "2017-07-05",
    coords:             [-9.1, 38.7],
    trip_type:          ["Séjour"],
    airport_dep:        "Lisbonne",
    airport_dep_coords: [-9.1359, 38.7756],
    airport_ret:        "Lisbonne",
    airport_ret_coords: [-9.1359, 38.7756],
    stops:              ["Sesimbra"],
    photos:             0,
    cover:              1,
    intro:              "Retour à Lisbonne en été, avec plus de temps pour se perdre dans l'Alfama.",
    comments:           null,
  },
  {
    nr:                 13,
    id:                 "canada-201707",
    country:            "Canada",
    continent:          "Amérique du Nord",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2017-07-16",
    date_ret:           "2017-07-31",
    coords:             [-79.4, 43.7],
    trip_type:          ["Roadtrip"],
    airport_dep:        "Toronto",
    airport_dep_coords: [-79.6248, 43.6777],
    airport_ret:        "Québec",
    airport_ret_coords: [-71.3933, 46.7911],
    stops:              ["Toronto", "Ottawa", "Montréal", "Trois-Rivières", "La Sacacomie", "St-Félicien", "Saguenay", "Tadoussac", "Québec"],
    photos:             0,
    cover:              1,
    intro:              "Premier roadtrip canadien entre Toronto et le Québec. Niagara Falls, les plaines d'Abraham.",
    comments:           null,
  },
  {
    nr:                 14,
    id:                 "norvege-201712",
    country:            "Norvège",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2017-12-25",
    date_ret:           null,
    coords:             [10.75, 59.91],
    trip_type:          ["Séjour"],
    airport_dep:        "Oslo",
    airport_dep_coords: [11.1004, 60.1939],
    airport_ret:        "Oslo",
    airport_ret_coords: [11.1004, 60.1939],
    stops:              ["Oslo"],
    photos:             0,
    cover:              1,
    intro:              "Oslo en décembre, dans l'obscurité presque totale. Les musées, le port.",
    comments:           null,
  },
  {
    nr:                 15,
    id:                 "usa-201807",
    country:            "États-Unis",
    continent:          "Amérique du Nord",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2018-07-23",
    date_ret:           null,
    coords:             [-115.1, 36.2],
    trip_type:          ["Roadtrip"],
    airport_dep:        "Las Vegas",
    airport_dep_coords: [-115.1523, 36.084],
    airport_ret:        "San Francisco",
    airport_ret_coords: [-122.3789, 37.6213],
    stops:              ["Las Vegas", "Page", "Kayenta", "Kingman", "Death Valley", "Pioneertown", "Los Angeles", "Cambria", "San Francisco"],
    photos:             0,
    cover:              1,
    intro:              "Roadtrip Las Vegas → San Francisco via Monument Valley et la côte pacifique.",
    comments:           null,
  },
  {
    nr:                 16,
    id:                 "croatie-201809",
    country:            "Croatie",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2018-09-30",
    date_ret:           null,
    coords:             [15.2, 45.1],
    trip_type:          ["Séjour"],
    airport_dep:        "Split",
    airport_dep_coords: [16.298, 43.5389],
    airport_ret:        "Split",
    airport_ret_coords: [16.298, 43.5389],
    stops:              ["Turanj", "Split"],
    photos:             0,
    cover:              1,
    intro:              "Split et sa vieille ville construite dans le palais de Dioclétien.",
    comments:           null,
  },
  {
    nr:                 17,
    id:                 "portugal-201904",
    country:            "Portugal",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2019-04-14",
    date_ret:           null,
    coords:             [-9.1, 38.7],
    trip_type:          ["Séjour"],
    airport_dep:        "Lisbonne",
    airport_dep_coords: [-9.1359, 38.7756],
    airport_ret:        "Lisbonne",
    airport_ret_coords: [-9.1359, 38.7756],
    stops:              ["Sesimbra"],
    photos:             0,
    cover:              1,
    intro:              "Lisbonne au printemps — les jacarandas en fleur, les terrasses animées.",
    comments:           null,
  },
  {
    nr:                 18,
    id:                 "islande-201907",
    country:            "Islande",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2019-07-23",
    date_ret:           "2019-08-07",
    coords:             [-19.0, 64.9],
    trip_type:          ["Roadtrip"],
    airport_dep:        "Keflavik",
    airport_dep_coords: [-22.6056, 63.985],
    airport_ret:        "Reykjavik",
    airport_ret_coords: [-21.9406, 64.13],
    stops: ["Stops to define..."],
    photos:             0,
    cover:              1,
    intro:              "L'Islande — une île au bout du monde. Geysers, cascades, champs de lave et nuits blanches.",
    comments:           null,
  },
  {
    nr:                 19,
    id:                 "autriche-201910",
    country:            "Autriche",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2019-10-29",
    date_ret:           null,
    coords:             [14.5, 47.5],
    trip_type:          ["Séjour"],
    airport_dep:        "Vienne",
    airport_dep_coords: [16.5697, 48.1103],
    airport_ret:        "Vienne",
    airport_ret_coords: [16.5697, 48.1103],
    stops:              ["Vienne"],
    photos:             0,
    cover:              1,
    intro:              "Vienne et son faste impérial. Les musées, les cafés historiques, les palais.",
    comments:           null,
  },
  {
    nr:                 20,
    id:                 "norvege-202007",
    country:            "Norvège",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2020-07-28",
    date_ret:           "2020-08-06",
    coords:             [10.7, 59.9],
    trip_type:          ["Séjour"],
    airport_dep:        "Stavanger",
    airport_dep_coords: [5.6378, 58.8768],
    airport_ret:        "Stavanger",
    airport_ret_coords: [5.6378, 58.8768],
    stops:              ["Ogna", "Mandal"],
    photos:             0,
    cover:              1,
    intro:              "Retour en Norvège malgré tout, en pleine pandémie. Les fjords n'avaient jamais été aussi silencieux.",
    comments:           null,
  },
  {
    nr:                 21,
    id:                 "pologne-202107",
    country:            "Pologne",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2021-07-27",
    date_ret:           "2021-08-07",
    coords:             [21.0, 52.2],
    trip_type:          ["Roadtrip"],
    airport_dep:        "Varsovie",
    airport_dep_coords: [20.9671, 52.1657],
    airport_ret:        "Varsovie",
    airport_ret_coords: [20.9671, 52.1657],
    stops:              ["Varsovie"],
    photos:             0,
    cover:              1,
    intro:              "Retour à Cracovie en été. La place principale, le château du Wawel.",
    comments:           null,
  },
  {
    nr:                 22,
    id:                 "irlande-202111",
    country:            "Irlande",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2021-11-06",
    date_ret:           "2021-11-14",
    coords:             [-8.2, 53.1],
    trip_type:          ["Roadtrip"],
    airport_dep:        "Dublin",
    airport_dep_coords: [-6.27, 53.4213],
    airport_ret:        "Dublin",
    airport_ret_coords: [-6.27, 53.4213],
    stops: ["Stops to define..."],
    photos:             0,
    cover:              1,
    intro:              "Dublin en novembre, sous la pluie. Les pubs chaleureux, la musique live.",
    comments:           null,
  },
  {
    nr:                 23,
    id:                 "portugal-202205",
    country:            "Portugal",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2022-05-19",
    date_ret:           null,
    coords:             [-8.6, 41.1],
    trip_type:          ["Roadtrip"],
    airport_dep:        "Porto",
    airport_dep_coords: [-8.6814, 41.2481],
    airport_ret:        "Lisbonne",
    airport_ret_coords: [-9.1359, 38.7756],
    stops: ["Stops to define..."],
    photos:             0,
    cover:              1,
    intro:              "Du nord au sud — Porto et ses caves à vin, la vallée du Douro, puis Lisbonne.",
    comments:           null,
  },
  {
    nr:                 24,
    id:                 "finlande-202207",
    country:            "Finlande;Suède",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2022-07-18",
    date_ret:           "2022-08-03",
    coords:             [25.0, 60.2],
    trip_type:          ["Roadtrip"],
    airport_dep:        "Helsinki",
    airport_dep_coords: [24.9633, 60.3172],
    airport_ret:        "Helsinki",
    airport_ret_coords: [24.9633, 60.3172],
    stops: ["Stops to define..."],
    photos:             0,
    cover:              1,
    intro:              "Retour en Finlande, avec une escapade côté suédois. L'archipel, les ferries.",
    comments:           null,
  },
  {
    nr:                 25,
    id:                 "danemark-202212",
    country:            "Danemark",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2022-12-26",
    date_ret:           "2023-01-02",
    coords:             [10.2, 55.7],
    trip_type:          ["Séjour"],
    airport_dep:        "Copenhague",
    airport_dep_coords: [12.6561, 55.618],
    airport_ret:        "Copenhague",
    airport_ret_coords: [12.6561, 55.618],
    stops:              ["Copenhague"],
    photos:             0,
    cover:              1,
    intro:              "Copenhague en décembre — Nyhavn sous les lumières de Noël, le design danois.",
    comments:           null,
  },
  {
    nr:                 26,
    id:                 "canada-202307",
    country:            "Canada",
    continent:          "Amérique du Nord",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2023-07-16",
    date_ret:           null,
    coords:             [-63.6, 44.6],
    trip_type:          ["Roadtrip"],
    airport_dep:        "Halifax",
    airport_dep_coords: [-63.5086, 44.8808],
    airport_ret:        "Halifax",
    airport_ret_coords: [-63.5086, 44.8808],
    stops: ["Stops to define..."],
    photos:             0,
    cover:              1,
    intro:              "Halifax et les Maritimes canadiennes — la côte Atlantique sauvage, les homards.",
    comments:           null,
  },
  {
    nr:                 27,
    id:                 "nzl-202310",
    country:            "Nouvelle-Zélande",
    continent:          "Océanie",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2023-10-12",
    date_ret:           "2023-11-04",
    coords:             [172.6, -41.3],
    trip_type:          ["Roadtrip"],
    airport_dep:        "Auckland",
    airport_dep_coords: [174.785, -37.0082],
    airport_ret:        "Auckland",
    airport_ret_coords: [174.785, -37.0082],
    stops:              ["Stops to define..."],
    photos:             0,
    cover:              1,
    intro:              "La Nouvelle-Zélande — un pays qui tient toutes ses promesses.",
    comments:           null,
  },
  {
    nr:                 28,
    id:                 "usa-202312",
    country:            "États-Unis",
    continent:          "Amérique du Nord",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2023-12-25",
    date_ret:           "2024-01-02",
    coords:             [-87.6, 41.9],
    trip_type:          ["Séjour", "Roadtrip"],
    airport_dep:        "Chicago",
    airport_dep_coords: [-87.9048, 41.9742],
    airport_ret:        "Chicago",
    airport_ret_coords: [-87.9048, 41.9742],
    stops:              ["Chicago", "Valders"],
    photos:             0,
    cover:              1,
    intro:              "Chicago en décembre — l'architecture monumentale, le lac Michigan gelé.",
    comments:           null,
  },
  {
    nr:                 29,
    id:                 "portugal-202402",
    country:            "Portugal",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2024-02-22",
    date_ret:           "2024-02-27",
    coords:             [-9.1, 38.7],
    trip_type:          ["Séjour"],
    airport_dep:        "Lisbonne",
    airport_dep_coords: [-9.1359, 38.7756],
    airport_ret:        "Lisbonne",
    airport_ret_coords: [-9.1359, 38.7756],
    stops:              ["Sesimbra"],
    photos:             0,
    cover:              1,
    intro:              "Lisbonne en hiver, presque déserte. Les ruelles de l'Alfama pour soi seul.",
    comments:           "Sesimbra avec la Tesla?",
  },
  {
    nr:                 30,
    id:                 "japon-202403",
    country:            "Japon",
    continent:          "Asie",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2024-03-26",
    date_ret:           "2024-04-15",
    coords:             [139.7, 35.7],
    trip_type:          ["Roadtrip"],
    airport_dep:        "Narita",
    airport_dep_coords: [140.3929, 35.7653],
    airport_ret:        "Narita",
    airport_ret_coords: [140.3929, 35.7653],
    stops:              ["Tokyo", "Hakone", "Asakawa", "Fujikawaguchiko", "Takayama", "Tajimi", "Nara", "Kyoto", "Narita"],
    photos:             0,
    cover:              1,
    intro:              "Le Japon au moment des cerisiers en fleur — hanami à Kyoto, Fuji sous la neige.",
    comments:           null,
  },
  {
    nr:                 31,
    id:                 "tanzanie-202407",
    country:            "Tanzanie",
    continent:          "Afrique",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2024-07-14",
    date_ret:           "2024-07-27",
    coords:             [34.9, -6.4],
    trip_type:          ["Safari", "Séjour"],
    airport_dep:        "Kilimanjaro",
    airport_dep_coords: [37.0745, -3.4294],
    airport_ret:        "Zanzibar",
    airport_ret_coords: [39.2249, -6.222],
    stops:              ["Kilimandjaro", "Arusha", "Parc du Tarangire", "Lac Manyara", "Ngorongoro", "Serengeti", "Arusha", "Kilimandjaro", "Zanzibar City"],
    photos:             12,
    cover:              6,
    intro:              "Safari dans le Serengeti et sur le cratère du Ngorongoro, puis Zanzibar pour souffler.",
    comments:           null,
  },
  {
    nr:                 32,
    id:                 "espagne-202410",
    country:            "Espagne",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste", "Mar"],
    date_dep:           "2024-10-03",
    date_ret:           "2024-10-07",
    coords:             [-0.4, 39.5],
    trip_type:          ["Séjour"],
    airport_dep:        "Valence",
    airport_dep_coords: [-0.4815, 39.4893],
    airport_ret:        "Valence",
    airport_ret_coords: [-0.4815, 39.4893],
    stops:              ["Valence"],
    photos:             0,
    cover:              1,
    intro:              "Valence et sa paella, son architecture futuriste de la Cité des Arts et des Sciences.",
    comments:           null,
  },
  {
    nr:                 33,
    id:                 "norvege-202501",
    country:            "Norvège",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2025-01-04",
    date_ret:           "2025-01-06",
    coords:             [18.9189, 69.6833],
    trip_type:          ["Roadtrip"],
    airport_dep:        "Tromsø",
    airport_dep_coords: [18.9189, 69.6833],
    airport_ret:        "Tromsø",
    airport_ret_coords: [18.9189, 69.6833],
    stops: ["Stops to define..."],
    photos:             0,
    cover:              1,
    intro:              "Tromsø en janvier — aurores boréales, nuit polaire et paysages arctiques.",
    comments:           null,
  },
  {
    nr:                 34,
    id:                 "canada-202507",
    country:            "Canada",
    continent:          "Amérique du Nord",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2025-07-04",
    date_ret:           null,
    coords:             [-135.1, 60.7],
    trip_type:          ["Roadtrip"],
    airport_dep:        "Whitehorse",
    airport_dep_coords: [-135.0674, 60.7096],
    airport_ret:        "Whitehorse",
    airport_ret_coords: [-135.0674, 60.7096],
    stops: ["Stops to define..."],
    photos:             16,
    cover:              1,
    intro:              "Le Yukon — une frontière sauvage. Whitehorse, la route de l'Alaska.",
    comments:           null,
  },
  {
    nr:                 35,
    id:                 "vietnam-202604",
    country:            "Vietnam;Cambodge",
    continent:          "Asie",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2026-04-01",
    date_ret:           null,
    coords:             [105.85, 21.03],
    trip_type:          ["Roadtrip"],
    airport_dep:        "Hanoï",
    airport_dep_coords: [105.8072, 21.2212],
    airport_ret:        "Hanoï",
    airport_ret_coords: [105.8072, 21.2212],
    stops:              ["Stops to define..."],
    photos:             0,
    cover:              1,
    intro:              "Hanoï, la baie d'Ha Long, Hội An — le Vietnam du nord au sud, puis le Cambodge et les temples d'Angkor.",
    comments:           null,
  },
  {
    nr:                 36,
    id:                 "norvege-202606",
    country:            "Norvège",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2026-06-09",
    date_ret:           "2026-06-14",
    coords:             [5.25, 59.3],
    trip_type:          ["Séjour"],
    airport_dep:        "Bergen",
    airport_dep_coords: [5.2184, 60.2934],
    airport_ret:        "Bergen",
    airport_ret_coords: [5.2184, 60.2934],
    stops:              ["Karmøy"],
    photos:             0,
    cover:              1,
    intro:              "Karmøy — l'île ancestrale de la famille. Un retour aux racines norvégiennes.",
    comments:           null,
  },
  {
    nr:                 37,
    id:                 "ecosse-202607",
    country:            "Écosse",
    continent:          "Europe",
    published:          true,
    travellers:         ["Tip", "Ste"],
    date_dep:           "2026-07-01",
    date_ret:           "2026-07-02",
    coords:             [-3.1883, 55.9533],  /* Édimbourg */
    trip_type:          ["Roadtrip"],
    airport_dep:        "Édimbourg",
    airport_dep_coords: [-3.3725, 55.9500],
    airport_ret:        "Édimbourg",
    airport_ret_coords: [-3.3725, 55.9500],
    stops:              ["Stops to define..."],
    photos:             0,
    cover:              1,
    intro:              "Le nord sauvage de l'Écosse en camper — Highlands, lochs et côtes battues par le vent.",
    comments:           null,
  }
];